# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: yarn install
        run: yarn install --frozen-lockfile --network-timeout 120000

      # Runs a single command using the runners shell
      - name: yarn test
        env:
          DB_DRIVER: postgres
        run: yarn run test --forceExit

      - name: uploader
        if: ${{ always() }}
        run: 'curl -X POST -H "Authorization: Token token=${{ secrets.BK_TOKEN }}" -F "format=junit" -F "data=@junit.xml" -F "run_env[CI]=github" -F "run_env[key]=$GITHUB_ACTION-$GITHUB_RUN_NUMBER-$GITHUB_RUN_ATTEMPT" -F "run_env[number]=$GITHUB_RUN_NUMBER" -F "run_env[job_id]=$GITHUB_JOB" -F "run_env[branch]=$GITHUB_REF_NAME" -F "run_env[commit_sha]=$GITHUB_SHA" -F "run_env[url]=$GITHUB_REPOSITORY" https://analytics-api.buildkite.com/v1/uploads'
